apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-candidate-a
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: candidate-a
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:a1961605f74005bb7872fcb5289b96d53253816871e2a75feed580a8ef77bae3
    source:
      repository: cogni-dao/toks4
      sha: 947c241ffa0cf0e31fb614b81e6837633f891e98
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:f670a4a48f3343ede987c5e20d3a8ae00a8b311d558414a4a0ca40470708bde9
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:4c9f62667b989adfc179039cee64e0b1650693f50c505ce10b69b841ff0732b4
  workload:
    name: toks4
    publicHost: toks4-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
          - key: LITELLM_VIRTUAL_KEY
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
