apiVersion: compute.cogni.io/v1alpha1
kind: ComputeWorkload
metadata:
  name: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  namespace: cogni-candidate-a
  labels:
    cogni.io/node-id: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
    cogni.io/environment: candidate-a
    cogni.io/node: toks4
spec:
  nodeId: 72aa130b-f0ad-495a-a061-9ee1f9c9525d
  environment: candidate-a
  bundle:
    ref: ghcr.io/cogni-dao/toks4@sha256:e417ed03c92de8e380c571542a3b4bf1a8bc0d14cdd6e576e53b72d35057939b
    source:
      repository: cogni-dao/toks4
      sha: fef24a3f7d86359ef3d8c8dd070b380cbf5b3f4b
    artifacts:
      - name: app
        image: ghcr.io/cogni-dao/toks4@sha256:3782d443c51c83e6400161dae8b72510d03b1b9243491982acb3c837ec0d9cb6
      - name: echo-sidecar
        image: ghcr.io/cogni-dao/toks4-echo-sidecar@sha256:47e0a3df7f3525a5dbec9039509bc3d414b2543b8ed4c52db91495804dacc691
  workload:
    name: toks4
    publicHost: toks4-test.cognidao.org
    services:
      - name: app
        artifact: app
        runtimeProfile: cogni-node-app-v1
        secretRefs:
          - key: AUTH_SECRET
          - key: DATABASE_URL
          - key: DATABASE_SERVICE_URL
          - key: SCHEDULER_API_TOKEN
          - key: BILLING_INGEST_TOKEN
          - key: LITELLM_VIRTUAL_KEY
        port: 3200
        visibility: public
        bindings:
          ECHO_SIDECAR_URL: echo-sidecar
        bindHost: 0.0.0.0
        cpuUnits: 2
        memoryMi: 2048
        storageMi: 4096
      - name: echo-sidecar
        artifact: echo-sidecar
        port: 9100
        visibility: private
        bindings: {}
        bindHost: 0.0.0.0
        cpuUnits: 0.1
        memoryMi: 128
        storageMi: 128
